# Site settings
title: "Test"
author: "Drew Hodge"
description: "description"
keywords: "keyword1, keyword2, keyword3"
biography: "biography"
colophon: "Adapted from 'papyrus-theme' © MMXIII — MMXVI by Hugo Sereno Ferreira.<br>Content available under <a href='http://creativecommons.org/licenses/by-nc-sa/4.0/'>Creative Commons (BY-NC-SA)</a> unless otherwise noted.<br>This site is hosted at <a href='https://pages.github.com/'>Github Pages</a> and created with <a href='http://jekyllrb.com/'>Jekyll</a>."

github: [metadata]
encoding: UTF-8

# baseurl: ""
# url: "http://hugosereno.eu"

# twitter_username: ferreira_hugo
# github_username: hugoferreira
# linkedin_username: hugoserenoferreira
# facebook_username: hugo.sereno.ferreira
# google-analytics: UA-69060-5

# simple_search: http://google.com/search
# markdown: kramdown
# highlighter: rouge
# permalink: /blog/:year/:month/:day/:title/

# theme: minima
# remote-theme: lanyon
